[#ftl]
[@b.navmenu title="权限管理"]
	[@b.navitem title="控制台" href="index"/]
	[@ems.guard res="/security/user"][@b.navitem title="用户" href="/security/user"  target=""/][/@]
	[@ems.guard res="/security/group"][@b.navitem title="用户组" href="/security/group"  target=""/][/@]
	[@ems.guard res="/security/menu"][@b.navitem title="菜单" href="/security/menu"  target=""/][/@]
	[@ems.guard res="/security/sub-system"][@b.navitem title="子系统" href="/security/sub-system"  target=""/][/@]
	[@ems.guard res="/security/resource"][@b.navitem title="资源" href="/security/resource"  target=""/][/@]
	[@ems.guard res="/security/restrict-meta"][@b.navitem title="数据权限" href="/security/restrict-meta"  target=""/][/@]
	[#--
	[@ems.guard res="/security/restrict-meta"][@b.navitem title="业务数据限制域" href="/security/restrict-meta!fields" /][/@]
	[@ems.guard res="/security/restrict-meta"][@b.navitem title="业务数据和模式" href="/security/restrict-meta!entities" /][/@]
	--]
	[@b.navitem title="我的账户" href="/security/my?nav=true"  target=""/]
[/@]