[#ftl]
[@b.head/]
[#assign labInfo][#if userGroup.id??]${b.text("action.modify")}[#else]${b.text("action.new")}[/#if] 用户组[/#assign]
[@b.toolbar title=labInfo]bar.addBack();[/@]
[@b.form name="groupForm" action="!save" class="listform" title="用户组信息" theme="list"]
			[@b.textfield name="userGroup.name" label="common.name" value="${userGroup.name!}" required="true" maxlength="50"/]
			[@b.radios label="common.status"  name="userGroup.enabled"value=userGroup.enabled items="1:action.activate,0:action.freeze"/]
			[@b.select label="适用身份" required="true"name="userGroup.category.id" value=(userGroup.category.id)!  style="width:100px;" items=categories option="id,title"/]
			[@b.textfield name="userGroup.remark" label="common.remark" value="${userGroup.remark!}" maxlength="50"/]
			[@b.formfoot]
				<input type="hidden" name="userGroup.id" value="${userGroup.id!}" />
				[@b.redirectParams/]
				[@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
			[/@]
	[/@]
	[#if userGroup.id??]
	[@b.tab label="全局数据权限" id="group_restriction" href="restriction!info?forEdit=1&restrictionType=group&restriction.holder.id=${userGroup.id}" /]
	[/#if]
[@b.foot/]