[#ftl]
[@b.navmenu title="字典管理"]
	[@ems.guard res="/security/index"][@b.navitem title="控制台" href="index" target=""/][/@]
	[@ems.guard res="/system/dict-type"][@b.navitem title="字典类型" href="/system/dict-type" target="" /][/@]
	[@ems.guard res="/system/dict-data"][@b.navitem title="字典数据" href="/system/dict-data" target="" /][/@]
	[@ems.guard res="/system/system-argument"][@b.navitem title="系统参数" href="system-argument!edit"  target=""/][/@]
[/@]