[#ftl]
[@b.head/]
	[@b.toolbar title="找回密码"][/@]
	[@b.form title="找回密码" action="!save" theme="form"]
		[@b.email label="common.email" name="user.mail" value=(user.mail)! required="true" maxlength="50" style="width:300px;"/]
		[@b.textfield label="用户名" name="user.name" value=(user.name)! required="true" maxlength="50" style="width:300px;"/]
		[@b.textfield label="姓名" name="user.fullname" value=(user.fullname)! required="true" style="width:300px;"/]
		[@b.captcha/]
		[@b.formfoot]
			[@b.redirectParams/]
			[@b.reset/][@b.submit value="action.submit" /]
		[/@]
	[/@]
[@b.foot/]