[#ftl]
[@b.navmenu title="系统信息"]
	[@ems.guard res="/system/info"]
	[@b.navitem title="系统信息" href="info" target=""/]
	[@b.navitem title="系统状态" href="info!status"  target=""/]
	[@b.navitem title="系统属性" href="info!properties"  target=""/]
	[/@]
	[@ems.guard res="/system/property"][@b.navitem title="系统配置" href="property"  target=""/][/@]
	[@ems.guard res="/system/file"][@b.navitem title="文件浏览" href="file"  target=""/][/@]
[/@]