[#ftl]
[@b.head/]
[#include "../nav.ftl"/]
[@b.form name="userSearchForm" action="!search" title="ui.searchForm" target="userlist" theme="search"]
	[@b.textfields names="user.name,user.fullname,user.creator.fullname,groupName;entity.group"/]
	[@b.select name="categoryId" label="entity.userCategory" items=categories empty="..." option="id,title"/]
	[@b.select name="user.enabled" label="common.status" value="1" empty="..." items={'1':'${b.text("action.activate")}','0':'${b.text("action.freeze")}'}/]
[/@]
[@b.div id="userlist" href="!search" /]
[@b.foot/]