[#ftl]
[@b.head/]
[@b.toolbar title="字典数据" entityId=dictData.id!0]bar.addBack();[/@]
[@b.form action="!save" title="字典数据" theme="list"]
	[@b.textfield name="dictData.code" label="common.code" value="${dictData.code!}" required="true" maxlength="50"/]
	[@b.textfield name="dictData.name" label="common.name" value="${dictData.name!}" required="true" maxlength="30"/]
	[@b.textfield name="dictData.enName" label="英文名称" value="${dictData.enName!}" maxlength="50"/]
	[@b.textfield name="dictData.gbxb" label="国标校标" value="${dictData.gbxb!}" maxlength="50"/]
	[@b.select label="字典类型" required="true" name="dictData.dictType.id" empty="请选择..." value=(dictData.dictType.id)!  style="width:160px;" items=dictTypes option="id,name"/]
	[@b.radios label="common.status"  name="dictData.enabled" value=dictData.enabled items="1:启用,0:禁用"/]
	[@b.formfoot]
		<input type="hidden" name="dictData.id" value="${dictData.id!}" />
		[@b.redirectParams/]
		[@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
	[/@]
[/@]
[@b.foot/]